### ISSUE TITLE
Import modules from same or parent directory

### ISSUE THREAD

**Issue by jacobcui** [alexeikostevich/python-blog#2]
https://github.com/alexeikostevich/python-blog/blob/3511c7d7da79f96097031dbbf5d56ea588a64ef8/pythonblog/blog/repository.py#L4

I think app engine will recognise the application's base directory as where the app.yaml file is and you can import parent module directly in child module. e.g:

app_root / view / foo.py
app_root / model / user.py

Let's say in foo.py you want to import a datastore model User from user.py, you can do simply like this in foo.py:

````
from model.user import User
````

**Comment by alexeikostevich** [comment]
This a great catch!

Looking at your comment, I realized that PEP8 discourages from using relative imports at all: https://www.python.org/dev/peps/pep-0008/#imports

From the other side, Django uses relative imports in their examples: https://docs.djangoproject.com/en/1.11/intro/tutorial03/#write-views-that-actually-do-something

Turning this into account, does it make sense to establish the following rule?
- Use relative imports within a single Django application (conceptually, a package) to be less 
- Use absolute imports to reference classes from another Django application (like _common_)

For example in *pythonblog/blog/view/index_view.py*:
````
# Reference modules from the common app
from pythonblog.common.auth_view_mixins import AuthContextMixin
# Reference modules within the same app
from ..repository import PostRepository
from .mixins import PageViewMixin
````

Please, could you share what approach do you prefer?

Thank you for paying my attention at this!

**Comment by alexeikostevich** [comment]
Switched to absolute imports for consistency and readability: https://github.com/alexeikostevich/python-blog/commit/e6676f0dda644aa42aeb24572b0409d8d366b4dd
