### ISSUE TITLE
Don't forget to invoke unittest.main() at the end.

### ISSUE THREAD

**Issue by jacobcui** [alexeikostevich/python-blog#3]
https://github.com/alexeikostevich/python-blog/blob/3511c7d7da79f96097031dbbf5d56ea588a64ef8/pythonblog/blog/tests/test_repository.py#L1

To make the test runnable, we need to invoke unittest.main() like:

````
if __name__ == '__main__':
    unittest.main()
````

so normally at the begging of the unittest file, we'll import unittest directly likt:

````
import unittest

class MyUnitTest(unittest.TestCase):
  ....

if __name__ == '__main__':
    unittest.main()
````

**Comment by alexeikostevich** [comment]
That is a great tip. Working on this...

**Comment by alexeikostevich** [comment]
Fixed with https://github.com/alexeikostevich/python-blog/commit/671de8be8ae125c2ed076d7549fa1151891d3367.
